In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#tensorflow
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

In [19]:
#Uploading Data
df=pd.read_csv('train.csv')
dt=pd.read_csv('test.csv')

In [20]:
#Checking null values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df=df.drop(columns=['Cabin'])
dt=dt.drop(columns=['Cabin'])

In [22]:
#Converting male to 1 and female to 0
for i in range(df.shape[0]):
    if df.iat[i,4]=='male':
        df.iat[i,4]=1
    else:df.iat[i,4]=0
        
for i in range(dt.shape[0]):
    if dt.iat[i,3]=='male':
        dt.iat[i,3]=1
    else:dt.iat[i,3]=0

In [23]:
#Removing Nan values for Age
for i in range(df.shape[0]):
    if pd.isna(df.iat[i,5]):
        df.iat[i,5]=df[(df.Sex==df.iat[i,4])&(df.Pclass==df.iat[i,2])].Age.mean()
        
for i in range(dt.shape[0]):
    if pd.isna(dt.iat[i,4]):
        dt.iat[i,4]=dt[(dt.Sex==dt.iat[i,3])&(dt.Pclass==dt.iat[i,1])].Age.mean()

In [24]:
#Removing Nan in Embarked
for i in range(df.shape[0]):
    if pd.isna(df.iat[i,8]):
        df.iat[i,8]='S'

In [25]:
#Dropping Fare
df=df.drop(columns=['Fare'])
dt=dt.drop(columns=['Fare'])

In [26]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.000000,1,0,A/5 21171,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.000000,1,0,PC 17599,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.000000,0,0,STON/O2. 3101282,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.000000,1,0,113803,S
4,5,0,3,"Allen, Mr. William Henry",1,35.000000,0,0,373450,S
5,6,0,3,"Moran, Mr. James",1,26.507589,0,0,330877,Q
6,7,0,1,"McCarthy, Mr. Timothy J",1,54.000000,0,0,17463,S
7,8,0,3,"Palsson, Master. Gosta Leonard",1,2.000000,3,1,349909,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",0,27.000000,0,2,347742,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",0,14.000000,1,0,237736,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",0,4.000000,1,1,PP 9549,S
11,12,1,1,"Bonnell, Miss. Elizabeth",0,58.000000,0,0,113783,S
12,13,0,3,"Saundercock, Mr. William Henry",1,20.000000,0,0,A/5. 2151,S
13,14,0,3,"Andersson, Mr. Anders Johan",1,39.000000,1,5,347082,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",0,14.000000,0,0,350406,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",0,55.000000,0,0,248706,S
16,17,0,3,"Rice, Master. Eugene",1,2.000000,4,1,382652,Q
17,18,1,2,"Williams, Mr. Charles Eugene",1,30.740707,0,0,244373,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",0,31.000000,1,0,345763,S
19,20,1,3,"Masselmani, Mrs. Fatima",0,21.750000,0,0,2649,C
20,21,0,2,"Fynney, Mr. Joseph J",1,35.000000,0,0,239865,S
21,22,1,2,"Beesley, Mr. Lawrence",1,34.000000,0,0,248698,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",0,15.000000,0,0,330923,Q
23,24,1,1,"Sloper, Mr. William Thompson",1,28.000000,0,0,113788,S
24,25,0,3,"Palsson, Miss. Torborg Danira",0,8.000000,3,1,349909,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",0,38.000000,1,5,347077,S
26,27,0,3,"Emir, Mr. Farred Chehab",1,26.507589,0,0,2631,C
27,28,0,1,"Fortune, Mr. Charles Alexander",1,19.000000,3,2,19950,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",0,21.750000,0,0,330959,Q
29,30,0,3,"Todoroff, Mr. Lalio",1,26.507589,0,0,349216,S
...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",1,21.000000,1,0,28134,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",0,48.000000,0,0,17466,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",0,21.750000,8,2,CA. 2343,S
864,865,0,2,"Gill, Mr. John William",1,24.000000,0,0,233866,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",0,42.000000,0,0,236852,S
866,867,1,2,"Duran y More, Miss. Asuncion",0,27.000000,1,0,SC/PARIS 2149,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",1,31.000000,0,0,PC 17590,S
868,869,0,3,"van Melkebeke, Mr. Philemon",1,26.507589,0,0,345777,S
869,870,1,3,"Johnson, Master. Harold Theodor",1,4.000000,1,1,347742,S
870,871,0,3,"Balkic, Mr. Cerin",1,26.000000,0,0,349248,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",0,47.000000,1,1,11751,S
872,873,0,1,"Carlsson, Mr. Frans Olof",1,33.000000,0,0,695,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",1,47.000000,0,0,345765,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",0,28.000000,1,0,P/PP 3381,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",0,15.000000,0,0,2667,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",1,20.000000,0,0,7534,S
877,878,0,3,"Petroff, Mr. Nedelio",1,19.000000,0,0,349212,S
878,879,0,3,"Laleff, Mr. Kristo",1,26.507589,0,0,349217,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",0,56.000000,0,1,11767,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",0,25.000000,0,1,230433,S
881,882,0,3,"Markun, Mr. Johann",1,33.000000,0,0,349257,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",0,22.000000,0,0,7552,S
883,884,0,2,"Banfield, Mr. Frederick James",1,28.000000,0,0,C.A./SOTON 34068,S
884,885,0,3,"Sutehall, Mr. Henry Jr",1,25.000000,0,0,SOTON/OQ 392076,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",0,39.000000,0,5,382652,Q
886,887,0,2,"Montvila, Rev. Juozas",1,27.000000,0,0,211536,S
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.000000,0,0,112053,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,21.750000,1,2,W./C. 6607,S
889,890,1,1,"Behr, Mr. Karl Howell",1,26.000000,0,0,111369,C
890,891,0,3,"Dooley, Mr. Patrick",1,32.000000,0,0,370376,Q

In [27]:
#Converting Embarked into numbers
for i in range(df.shape[0]):
    if df.iat[i,9]=='S':
        df.iat[i,9]=0
    if df.iat[i,9]=='C':
        df.iat[i,9]=1
    if df.iat[i,9]=='Q':
        df.iat[i,9]=2
        
for i in range(dt.shape[0]):
    if dt.iat[i,8]=='S':
        dt.iat[i,8]=0
    if dt.iat[i,8]=='C':
        dt.iat[i,8]=1
    if dt.iat[i,8]=='Q':
        dt.iat[i,8]=2

In [28]:
#Dropping unnessary fields
df=df.drop(columns=['Ticket','Name'])
dt=dt.drop(columns=['Ticket','Name'])

In [29]:
#Changing Index
df.index=df.PassengerId
df=df.drop(columns=['PassengerId'])
dt.index=dt.PassengerId
dt=dt.drop(columns=['PassengerId'])

In [30]:
#Normalizing Age
df.Age=df.Age/100
dt.Age=dt.Age/100

In [78]:
l0=tf.keras.layers.Dense(12,input_shape=(6,),activation='relu')
l1=tf.keras.layers.Dense(14,activation='relu')
l2=tf.keras.layers.Dense(12,activation='relu')
l3=tf.keras.layers.Dense(2,activation='sigmoid')

In [79]:
model=tf.keras.models.Sequential([l0,l1,l2,l3])
model.compile(optimizer=tf.train.AdamOptimizer(0.01),loss=tf.losses.softmax_cross_entropy,metrics=['mae'])

In [33]:
train=df.drop(columns=['Survived'])
labels=df['Survived']

In [37]:
train=train.to_numpy().astype(float)
labels=labels.to_numpy().astype(float)

In [41]:
labels

array([0., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0.])

In [43]:
df

             Survived  Pclass Sex       Age  SibSp  Parch Embarked
PassengerId
1                   0       3   1  0.220000      1      0        0
2                   1       1   0  0.380000      1      0        1
3                   1       3   0  0.260000      0      0        0
4                   1       1   0  0.350000      1      0        0
5                   0       3   1  0.350000      0      0        0
6                   0       3   1  0.265076      0      0        2
7                   0       1   1  0.540000      0      0        0
8                   0       3   1  0.020000      3      1        0
9                   1       3   0  0.270000      0      2        0
10                  1       2   0  0.140000      1      0        1
11                  1       3   0  0.040000      1      1        0
12                  1       1   0  0.580000      0      0        0
13                  0       3   1  0.200000      0      0        0
14                  0       3   1  0.390000      1      5        0
15                  0       3   0  0.140000      0      0        0
16                  1       2   0  0.550000      0      0        0
17                  0       3   1  0.020000      4      1        2
18                  1       2   1  0.307407      0      0        0
19                  0       3   0  0.310000      1      0        0
20                  1       3   0  0.217500      0      0        1
21                  0       2   1  0.350000      0      0        0
22                  1       2   1  0.340000      0      0        0
23                  1       3   0  0.150000      0      0        2
24                  1       1   1  0.280000      0      0        0
25                  0       3   0  0.080000      3      1        0
26                  1       3   0  0.380000      1      5        0
27                  0       3   1  0.265076      0      0        1
28                  0       1   1  0.190000      3      2        0
29                  1       3   0  0.217500      0      0        2
30                  0       3   1  0.265076      0      0        0
...               ...     ...  ..       ...    ...    ...      ...
862                 0       2   1  0.210000      1      0        0
863                 1       1   0  0.480000      0      0        0
864                 0       3   0  0.217500      8      2        0
865                 0       2   1  0.240000      0      0        0
866                 1       2   0  0.420000      0      0        0
867                 1       2   0  0.270000      1      0        1
868                 0       1   1  0.310000      0      0        0
869                 0       3   1  0.265076      0      0        0
870                 1       3   1  0.040000      1      1        0
871                 0       3   1  0.260000      0      0        0
872                 1       1   0  0.470000      1      1        0
873                 0       1   1  0.330000      0      0        0
874                 0       3   1  0.470000      0      0        0
875                 1       2   0  0.280000      1      0        1
876                 1       3   0  0.150000      0      0        1
877                 0       3   1  0.200000      0      0        0
878                 0       3   1  0.190000      0      0        0
879                 0       3   1  0.265076      0      0        0
880                 1       1   0  0.560000      0      1        1
881                 1       2   0  0.250000      0      1        0
882                 0       3   1  0.330000      0      0        0
883                 0       3   0  0.220000      0      0        0
884                 0       2   1  0.280000      0      0        0
885                 0       3   1  0.250000      0      0        0
886                 0       3   0  0.390000      0      5        2
887                 0       2   1  0.270000      0      0        0
888                 1       1   0  0.190000      0      0        0
889                 0       3   0  0.217500      1      2        0
890                 1       1   1  0.260000      0      0        1
891                 0       3   1  0.320000      0      0        2

[891 rows x 7 columns]

In [39]:
train=train.to_numpy().reshape((-1,6,1))

In [41]:
labels=labels.to_numpy().reshape((-1,1))

In [62]:
train=train.astype(float)

In [63]:
train

array([[3.    , 1.    , 0.22  , 1.    , 0.    , 0.    ],
       [1.    , 0.    , 0.38  , 1.    , 0.    , 1.    ],
       [3.    , 0.    , 0.26  , 0.    , 0.    , 0.    ],
       ...,
       [3.    , 0.    , 0.2175, 1.    , 2.    , 0.    ],
       [1.    , 1.    , 0.26  , 0.    , 0.    , 1.    ],
       [3.    , 1.    , 0.32  , 0.    , 0.    , 2.    ]])

In [54]:
train=train.reshape(891,6)

In [80]:
model.fit(train,labels,epochs=100)

Train on 891 samples
Epoch 1/100
891/891 [==============================] - 0s 177us/sample - loss: 0.5326 - mean_absolute_error: 0.4722
Epoch 2/100
891/891 [==============================] - 0s 101us/sample - loss: 0.5327 - mean_absolute_error: 0.4427
Epoch 3/100
891/891 [==============================] - 0s 111us/sample - loss: 0.5324 - mean_absolute_error: 0.4008
Epoch 4/100
891/891 [==============================] - 0s 98us/sample - loss: 0.5321 - mean_absolute_error: 0.3877
Epoch 5/100
891/891 [==============================] - 0s 99us/sample - loss: 0.5321 - mean_absolute_error: 0.3854
Epoch 6/100
891/891 [==============================] - 0s 100us/sample - loss: 0.5321 - mean_absolute_error: 0.3847
Epoch 7/100
891/891 [==============================] - 0s 148us/sample - loss: 0.5321 - mean_absolute_error: 0.3845
Epoch 8/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3843
Epoch 9/100
891/891 [==============================] - 0s 96us/sample - loss: 0.5321 - mean_absolute_error: 0.3842
Epoch 10/100
891/891 [==============================] - 0s 97us/sample - loss: 0.5321 - mean_absolute_error: 0.3841
Epoch 11/100
891/891 [==============================] - 0s 98us/sample - loss: 0.5321 - mean_absolute_error: 0.3841
Epoch 12/100
891/891 [==============================] - 0s 102us/sample - loss: 0.5321 - mean_absolute_error: 0.3840
Epoch 13/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3840
Epoch 14/100
891/891 [==============================] - 0s 120us/sample - loss: 0.5321 - mean_absolute_error: 0.3840
Epoch 15/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3840
Epoch 16/100
891/891 [==============================] - 0s 105us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 17/100
891/891 [==============================] - 0s 102us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 18/100
891/891 [==============================] - 0s 152us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 19/100
891/891 [==============================] - 0s 123us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 20/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 21/100
891/891 [==============================] - 0s 106us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 22/100
891/891 [==============================] - 0s 105us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 23/100
891/891 [==============================] - 0s 99us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 24/100
891/891 [==============================] - 0s 110us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 25/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 26/100
891/891 [==============================] - 0s 99us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 27/100
891/891 [==============================] - 0s 102us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 28/100
891/891 [==============================] - 0s 147us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 29/100
891/891 [==============================] - 0s 160us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 30/100
891/891 [==============================] - 0s 109us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 31/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 32/100
891/891 [==============================] - 0s 99us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 33/100
891/891 [==============================] - 0s 113us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 34/100
891/891 [==============================] - 0s 130us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 35/100
891/891 [==============================] - 0s 105us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 36/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 37/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 38/100
891/891 [==============================] - 0s 115us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 39/100
891/891 [==============================] - 0s 174us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 40/100
891/891 [==============================] - 0s 107us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 41/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 42/100
891/891 [==============================] - 0s 104us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 43/100
891/891 [==============================] - 0s 121us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 44/100
891/891 [==============================] - 0s 123us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 45/100
891/891 [==============================] - 0s 113us/sample - loss: 0.5321 - mean_absolute_error: 0.3839
Epoch 46/100
891/891 [==============================] - 0s 95us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 47/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 48/100
891/891 [==============================] - 0s 105us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 49/100
891/891 [==============================] - 0s 147us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 50/100
891/891 [==============================] - 0s 107us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 51/100
891/891 [==============================] - 0s 102us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 52/100
891/891 [==============================] - 0s 112us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 53/100
891/891 [==============================] - 0s 100us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 54/100
891/891 [==============================] - 0s 113us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 55/100
891/891 [==============================] - 0s 101us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 56/100
891/891 [==============================] - 0s 94us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 57/100
891/891 [==============================] - 0s 106us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 58/100
891/891 [==============================] - 0s 127us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 59/100
891/891 [==============================] - 0s 116us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 60/100
891/891 [==============================] - 0s 157us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 61/100
891/891 [==============================] - 0s 121us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 62/100
891/891 [==============================] - 0s 116us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 63/100
891/891 [==============================] - 0s 114us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 64/100
891/891 [==============================] - 0s 118us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 65/100
891/891 [==============================] - 0s 102us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 66/100
891/891 [==============================] - 0s 126us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 67/100
891/891 [==============================] - 0s 122us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 68/100
891/891 [==============================] - 0s 100us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 69/100
891/891 [==============================] - 0s 109us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 70/100
891/891 [==============================] - 0s 178us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 71/100

891/891 [==============================] - 0s 112us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 72/100
891/891 [==============================] - 0s 100us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 73/100
891/891 [==============================] - 0s 96us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 74/100
891/891 [==============================] - 0s 101us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 75/100
891/891 [==============================] - 0s 100us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 76/100
891/891 [==============================] - 0s 91us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 77/100
891/891 [==============================] - 0s 91us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 78/100
891/891 [==============================] - 0s 95us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 79/100
891/891 [==============================] - 0s 90us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 80/100
891/891 [==============================] - 0s 92us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 81/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 82/100
891/891 [==============================] - 0s 112us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 83/100
891/891 [==============================] - 0s 87us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 84/100
891/891 [==============================] - 0s 92us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 85/100
891/891 [==============================] - 0s 91us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 86/100
891/891 [==============================] - 0s 100us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 87/100
891/891 [==============================] - 0s 93us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 88/100
891/891 [==============================] - 0s 94us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 89/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 90/100
891/891 [==============================] - 0s 106us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 91/100
891/891 [==============================] - 0s 111us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 92/100
891/891 [==============================] - 0s 102us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 93/100
891/891 [==============================] - 0s 158us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 94/100
891/891 [==============================] - 0s 110us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 95/100
891/891 [==============================] - 0s 95us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 96/100
891/891 [==============================] - 0s 95us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 97/100
891/891 [==============================] - 0s 112us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 98/100
891/891 [==============================] - 0s 103us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 99/100
891/891 [==============================] - 0s 109us/sample - loss: 0.5321 - mean_absolute_error: 0.3838
Epoch 100/100
891/891 [==============================] - 0s 108us/sample - loss: 0.5321 - mean_absolute_error: 0.3838

In [56]:
test

NameError: name 'test' is not defined

In [73]:
dt=dt.astype(float)

In [81]:
result=model.predict(dt)

In [82]:
np.argmax(result,axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [74]:
dt

array([[3.        , 1.        , 0.345     , 0.        , 0.        ,
        2.        ],
       [3.        , 0.        , 0.47      , 1.        , 0.        ,
        0.        ],
       [2.        , 1.        , 0.62      , 0.        , 0.        ,
        2.        ],
       ...,
       [3.        , 1.        , 0.385     , 0.        , 0.        ,
        0.        ],
       [3.        , 1.        , 0.24525104, 0.        , 0.        ,
        0.        ],
       [3.        , 1.        , 0.24525104, 1.        , 1.        ,
        1.        ]])

In [83]:
from sklearn import svm

In [84]:
clf=svm.SVC()

In [85]:
clf.fit(train,labels)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [89]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    2
dtype: int64

In [90]:
dt.isna().sum()

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

In [184]:
model.predict(dt)

array([[0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.3855325 ],
       [0.38553253],
       [0.38553253]], dtype=float32)

In [36]:
test

NameError: name 'test' is not defined

In [185]:
model.predict_classes(dt)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [187]:
train

array([[ 3.  ,  1.  , 22.  ,  1.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  , 38.  ,  1.  ,  0.  ,  1.  ],
       [ 3.  ,  0.  , 26.  ,  0.  ,  0.  ,  0.  ],
       ...,
       [ 3.  ,  0.  , 21.75,  1.  ,  2.  ,  0.  ],
       [ 1.  ,  1.  , 26.  ,  0.  ,  0.  ,  1.  ],
       [ 3.  ,  1.  , 32.  ,  0.  ,  0.  ,  2.  ]])

In [17]:
df.shape

(891, 7)